force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Rev-{0000}</displayFormat>
        <label>Review Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/movieReviewChangeHandler.cls
public with sharing class movieReviewChangeHandler {
    
    public void afterInsert(List<Review__c> newReviews){
        this.task1(newReviews);
    }
    public void afterUpdate(List<Review__c> newReviews){
        this.task1(newReviews);
    }
    public void afterDelete(List<Review__c> oldReviews){
        this.task1(oldReviews);
    }

    public void task1(List<Review__c> newReviews){

        Set<Id> movieIds = new Set<Id>();
        
        for(Review__c rev : newReviews){
            movieIds.add(rev.Movie__c);
        }

        List<Movie__c> moviesToUpdate = new List<Movie__c>();
        for(Id movId : movieIds){
            Movie__c M = new Movie__c();
            M.Id = movId;
            M.Summary_Update__c = true;
            moviesToUpdate.add(M);
        }
        update moviesToUpdate;
    }
}