force-app/main/default/objects/Movie__c/fields/Genere__c.field-meta.xml
<CustomField>
    <fullName>Genere__c</fullName>
    <label>Genere</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Rommance</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Historical</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Poster__c.field-meta.xml
<CustomField>
    <fullName>Poster__c</fullName>
    <label>Poster</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula>Rating_Sum__c  /  Rating_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/movieList.cls
public without sharing class movieList {

    @AuraEnabled(cacheable=true)
    public static List<Movie__c> getMov(Integer PageNo,Integer Pagesize) {

        Integer offset = (PageNo - 1) * Pagesize;
        Integer totalRecords = [SELECT COUNT() FROM Movie__c];
        
        return [SELECT Id, Name, Release_Date__c,Poster__c, Genere__c,Rating__c FROM Movie__c LIMIT :Pagesize OFFSET :offset];
    }
}