force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula>Rating_Sum__c  /  Rating_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Rev-{0000}</displayFormat>
        <label>Review Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/movieSummryController.cls
public class movieSummryController {
    
    @AuraEnabled
    public static String getSummary(Id recordId){

        List<Review__c> reviews = [SELECT Id,Review__c FROM Review__c WHERE Movie__c = :recordId Order by CreatedDate ASC];

        Movie__c movie = [SELECT Name,Rating__c,Summary_Update__c,Summary__c FROM Movie__c Where Id = :recordId LIMIT 1];

        String allReviews = '';

        Decimal Rating = movie.Rating__c != null ? movie.Rating__c : 0;

        for(Review__c rev : reviews){
            if(rev.Review__c != null){
                allReviews += rev.Review__c + ' # ';
            }
        }

        if (movie.Summary_Update__c != true){
            return movie.Summary__c+' Summary is up to date.'; 
        }

        String summary = aiSummaryClass.getMovieSummary(movie.Name, allReviews, Rating);


        movie.Summary__c = summary;
        update movie;

        return summary;
    
    }


}